default_platform(:ios)

platform :ios do
  desc "Archive Selects and upload to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_API_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_content: ENV.fetch("APP_STORE_CONNECT_API_KEY"),
      is_key_content_base64: false
    )

    build_number = ENV["GITHUB_RUN_NUMBER"] || Time.now.strftime("%Y%m%d%H%M")
    increment_build_number(
      xcodeproj: "App/App.xcodeproj",
      build_number: build_number
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "App/App.xcodeproj",
      team_id: "L37YSKFC5X"
    )

    build_app(
      workspace: "App/App.xcworkspace",
      scheme: "App",
      configuration: "Release",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
