// data.jsx — factual film-location dataset for SELECTS
// All locations are real, visitable places. Blurbs are original summaries.

const FILMS = [
  {
    id: 'heat',
    title: 'Heat',
    year: 1995,
    director: 'Michael Mann',
    city: 'Los Angeles',
    region: 'California, USA',
    tag: 'Crime',
    runtime: '2h 50m',
    blurb: 'Michael Mann shot Heat almost entirely on real Los Angeles streets — no soundstages for the city. The result is a film map of mid-90s LA you can still walk today.',
    locations: [
      {
        id: 'heat-katemantilini',
        name: 'Kate Mantilini',
        address: '9101 Wilshire Blvd, Beverly Hills, CA',
        lat: 34.0668, lng: -118.4096,
        scene: 'The coffee scene',
        sceneNo: 'Sc. 47',
        timecode: '1:18:42',
        hero: true,
        distanceFt: 350,
        blurb: 'The only scene De Niro and Pacino share in the entire film. Mann shot it in a single corner booth of this Wilshire Blvd diner — two men, two coffees, one conversation about the lives they can\u2019t leave.',
        stories: [
          { t: 'One booth, one take of trust', b: 'The actors famously had never filmed together before this day. Mann kept the coverage simple — locked tripods, no rehearsal of the dialogue together — to catch a first meeting on camera.' },
          { t: 'The building is still here', b: 'The restaurant closed in 2014, but the distinctive curved-glass corner at Wilshire & Doheny is unchanged. Stand on the southwest corner for the exterior the cop tails him to.' },
        ],
      },
      {
        id: 'heat-downtown',
        name: '5th & Flower, Financial District',
        address: '5th St & S Flower St, Downtown LA, CA',
        lat: 34.0506, lng: -118.2560,
        scene: 'The bank shootout',
        sceneNo: 'Sc. 71',
        timecode: '1:52:10',
        distanceFt: 2.1,
        unit: 'mi',
        blurb: 'The running gun battle after the bank job was staged across real downtown blocks with live crowds cleared. The acoustics of the gunfire bouncing off the towers were recorded on location, not added later.',
        stories: [
          { t: 'No looping the gunfire', b: 'Sound designers kept the raw on-location report of the rifles echoing between the high-rises — a big reason the sequence still feels uniquely brutal.' },
        ],
      },
      {
        id: 'heat-drivein',
        name: 'Johnnie\u2019s Coffee Shop',
        address: '6101 Wilshire Blvd, Los Angeles, CA',
        lat: 34.0624, lng: -118.3618,
        scene: 'Stakeout exterior',
        sceneNo: 'Sc. 33',
        timecode: '0:54:03',
        distanceFt: 1.4,
        unit: 'mi',
        blurb: 'A 1956 Googie-style diner used across countless LA shoots. Its neon and boomerang roofline appear in the film\u2019s nighttime surveillance beats.',
        stories: [],
      },
      {
        id: 'heat-lax',
        name: 'LAX Runway 24',
        address: 'W Imperial Hwy, Los Angeles, CA',
        lat: 33.9438, lng: -118.4019,
        scene: 'The final confrontation',
        sceneNo: 'Sc. 88',
        timecode: '2:43:55',
        distanceFt: 6.8,
        unit: 'mi',
        blurb: 'The ending plays out on the open ground beside the airport, the landing lights of LAX strobing across the runway as the two men finish what the coffee scene started.',
        stories: [],
      },
    ],
  },
  {
    id: 'fast',
    title: 'The Fast and the Furious',
    year: 2001,
    director: 'Rob Cohen',
    city: 'Los Angeles',
    region: 'California, USA',
    tag: 'Action',
    runtime: '1h 46m',
    blurb: 'The film that turned a few Echo Park blocks and a Malibu seafood shack into pilgrimage sites for car culture worldwide.',
    locations: [
      {
        id: 'fast-bobs',
        name: 'Bob\u2019s Market',
        address: '1234 Bellevue Ave, Angelino Heights, LA',
        lat: 34.0716, lng: -118.2608,
        scene: 'Toretto\u2019s Market',
        sceneNo: 'Sc. 9',
        timecode: '0:11:20',
        distanceFt: 0.3,
        unit: 'mi',
        blurb: 'The real neighborhood corner store that played Toretto\u2019s Market & Cafe — where the tuna sandwich gets ordered "with no crust." Still an operating market; the owners are used to fans.',
        stories: [
          { t: 'The sandwich is on the menu', b: 'Locals will tell you the shop leaned into its fame. Order at the counter and look for the spot where Brian first walks in.' },
        ],
      },
      {
        id: 'fast-house',
        name: 'The Toretto House',
        address: '722 E Kensington Rd, Echo Park, LA',
        lat: 34.0769, lng: -118.2585,
        scene: 'The family dinner',
        sceneNo: 'Sc. 12',
        timecode: '0:23:40',
        distanceFt: 0.5,
        unit: 'mi',
        blurb: 'A private Victorian home up the hill from the market. The "you don\u2019t turn your back on family" grace-before-dinner was filmed in its small backyard.',
        stories: [
          { t: 'Please be kind \u2014 people live here', b: 'It remains a private residence. View it from the public sidewalk only.' },
        ],
      },
      {
        id: 'fast-neptunes',
        name: 'Neptune\u2019s Net',
        address: '42505 Pacific Coast Hwy, Malibu, CA',
        lat: 34.0469, lng: -118.9560,
        scene: 'The racer hangout',
        sceneNo: 'Sc. 20',
        timecode: '0:38:15',
        distanceFt: 22,
        unit: 'mi',
        blurb: 'A real biker-and-surfer seafood joint on the edge of Ventura County. The crew\u2019s burgers-and-beer scene plays out on its actual patio overlooking the Pacific.',
        stories: [
          { t: 'Still serving', b: 'Open since 1956. The patio and the PCH view are exactly as shot.' },
        ],
      },
    ],
  },
  {
    id: 'darkknight',
    title: 'The Dark Knight',
    year: 2008,
    director: 'Christopher Nolan',
    city: 'Chicago',
    region: 'Illinois, USA',
    tag: 'Action',
    runtime: '2h 32m',
    blurb: 'Nolan cast Chicago as Gotham, shooting on IMAX cameras in real streets, plazas and the canyons of Lower Wacker Drive.',
    locations: [
      {
        id: 'dk-lasalle',
        name: 'LaSalle St Canyon',
        address: 'W LaSalle St & Board of Trade, Chicago',
        lat: 41.8779, lng: -87.6324,
        scene: 'The truck flip',
        sceneNo: 'Sc. 51',
        timecode: '1:24:05',
        distanceFt: 800,
        blurb: 'The semi-truck flips end over end down LaSalle, the Board of Trade building framing the far end. The stunt was performed for real with a piston rig, captured in IMAX.',
        stories: [
          { t: 'A real truck, a real street', b: 'Nolan\u2019s team closed the financial canyon and flipped an 18-wheeler with a hydraulic ram rather than CGI.' },
        ],
      },
      {
        id: 'dk-postoffice',
        name: 'Old Chicago Post Office',
        address: '433 W Van Buren St, Chicago',
        lat: 41.8760, lng: -87.6395,
        scene: 'The opening bank heist',
        sceneNo: 'Sc. 1',
        timecode: '0:02:30',
        distanceFt: 0.4,
        unit: 'mi',
        blurb: 'The cavernous, then-abandoned postal hall played Gotham National Bank for the Joker\u2019s clown-mask robbery. Now restored as offices, the lobby is publicly accessible.',
        stories: [],
      },
      {
        id: 'dk-wacker',
        name: 'Lower Wacker Drive',
        address: 'Lower Wacker Dr, Chicago',
        lat: 41.8868, lng: -87.6325,
        scene: 'The Batpod chase',
        sceneNo: 'Sc. 54',
        timecode: '1:31:50',
        distanceFt: 0.6,
        unit: 'mi',
        blurb: 'The sodium-lit underworld beneath the city became the chase\u2019s tunnels. You can drive or walk the same stretch today.',
        stories: [],
      },
    ],
  },
  {
    id: 'skyfall',
    title: 'Skyfall',
    year: 2012,
    director: 'Sam Mendes',
    city: 'London',
    region: 'England, UK',
    tag: 'Action',
    runtime: '2h 23m',
    blurb: 'Bond\u2019s 50th-anniversary film is a love letter to London — its galleries, its river, its Underground.',
    locations: [
      {
        id: 'sky-gallery',
        name: 'The National Gallery',
        address: 'Trafalgar Square, London WC2N',
        lat: 51.5089, lng: -0.1283,
        scene: 'Bond meets Q',
        sceneNo: 'Sc. 22',
        timecode: '0:48:12',
        distanceFt: 120,
        blurb: 'Bond and the new young Q meet on a bench before Turner\u2019s "The Fighting Temeraire" \u2014 a painting of an old warship towed to scrap, mirroring the film\u2019s theme. Room 34 of the gallery; entry is free.',
        stories: [
          { t: 'The painting is the dialogue', b: 'Sit on the bench in Room 34 and the whole exchange about old things and new lands differently.' },
        ],
      },
      {
        id: 'sky-vauxhall',
        name: 'Vauxhall Cross (SIS Building)',
        address: '85 Albert Embankment, London SE1',
        lat: 51.4870, lng: -0.1240,
        scene: 'The MI6 attack',
        sceneNo: 'Sc. 8',
        timecode: '0:21:00',
        distanceFt: 1.1,
        unit: 'mi',
        blurb: 'The real headquarters of the Secret Intelligence Service. View the unmistakable green-and-cream ziggurat from across the Thames at Millbank.',
        stories: [],
      },
      {
        id: 'sky-whitehall',
        name: 'Whitehall & Westminster',
        address: 'Whitehall, London SW1A',
        lat: 51.5039, lng: -0.1265,
        scene: 'The final act setup',
        sceneNo: 'Sc. 40',
        timecode: '1:55:30',
        distanceFt: 0.7,
        unit: 'mi',
        blurb: 'The government quarter where the inquiry scenes were staged, steps from the Cenotaph and the rooftops Bond crosses.',
        stories: [],
      },
    ],
  },
  {
    id: 'taken',
    title: 'Taken',
    year: 2008,
    director: 'Pierre Morel',
    city: 'Paris',
    region: '\u00CEle-de-France, France',
    tag: 'Thriller',
    runtime: '1h 33m',
    blurb: 'A father tears across Paris in real time. The film threads recognizable bridges, rooftops and rail lines into one relentless chase.',
    locations: [
      {
        id: 'taken-birhakeim',
        name: 'Pont de Bir-Hakeim',
        address: 'Pont de Bir-Hakeim, 75015 Paris',
        lat: 48.8556, lng: 2.2876,
        scene: 'Under the bridge',
        sceneNo: 'Sc. 35',
        timecode: '1:02:40',
        distanceFt: 240,
        blurb: 'The double-deck steel bridge with the Métro running above — one of the most filmed structures in Paris. Walk the lower deck for the framing the chase uses.',
        stories: [
          { t: 'A bridge of a thousand films', b: 'Its riveted ironwork and river views make it a perennial location. The Eiffel Tower sits just upstream.' },
        ],
      },
      {
        id: 'taken-seine',
        name: 'Quais de Seine',
        address: 'Port de Grenelle, 75015 Paris',
        lat: 48.8520, lng: 2.2890,
        scene: 'The riverside pursuit',
        sceneNo: 'Sc. 38',
        timecode: '1:08:15',
        distanceFt: 0.3,
        unit: 'mi',
        blurb: 'The lower quays along the Seine, used for the on-foot pursuit. Accessible riverside walk, busy at golden hour.',
        stories: [],
      },
    ],
  },
];

// Flatten to pins for the globe / map
const ALL_PINS = [];
FILMS.forEach((f) => {
  f.locations.forEach((loc) => {
    ALL_PINS.push({ ...loc, filmId: f.id, filmTitle: f.title, filmYear: f.year, director: f.director, city: f.city, region: f.region });
  });
});

function getFilm(id) { return FILMS.find((f) => f.id === id); }
function getLocation(id) { return ALL_PINS.find((p) => p.id === id); }

// Cities for search → fly-to
const CITIES = [
  { id: 'la', name: 'Los Angeles', region: 'California, USA', lat: 34.05, lng: -118.24, count: 7 },
  { id: 'chicago', name: 'Chicago', region: 'Illinois, USA', lat: 41.88, lng: -87.63, count: 3 },
  { id: 'london', name: 'London', region: 'England, UK', lat: 51.50, lng: -0.12, count: 3 },
  { id: 'paris', name: 'Paris', region: '\u00CEle-de-France, France', lat: 48.85, lng: 2.29, count: 2 },
];

// Per-film poster colors — varied filmic hues so pins read as posters on the dark globe
const FILM_COLORS = {
  heat:       { a: '#ff5b3a', b: '#7a1505', mono: 'H' },
  fast:       { a: '#3aa0ff', b: '#0a2b66', mono: 'F' },
  darkknight: { a: '#3fd0c9', b: '#0c2e36', mono: 'DK' },
  skyfall:    { a: '#e8b24a', b: '#5a3c06', mono: 'S' },
  taken:      { a: '#5ad07a', b: '#0c3a1e', mono: 'T' },
};
function filmColor(id) { return FILM_COLORS[id] || { a: '#9b8cff', b: '#2b2350', mono: '\u25CF' }; }

Object.assign(window, { FILMS, ALL_PINS, CITIES, FILM_COLORS, getFilm, getLocation, filmColor });
